ktor:
    application:
        modules:
            - com.sanmati.ApplicationKt.module
    deployment:
        port: 8081
        host : "0.0.0.0"
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
  secret: "zen@01jain"
  validity : 604800000


postgres:
  url: "jdbc:postgresql://localhost:5432/sanmatimall"
  driver: "org.postgresql.Driver"
  user: "postgres"
  password : "Root@123"


